//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarmaladeApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxMarmalade
    {
        public BoxMarmalade()
        {
            this.TBM = new HashSet<TBM>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int MarmaladeID1 { get; set; }
        public int MarmaladeID2 { get; set; }
        public Nullable<int> MarmaladeID3 { get; set; }
        public Nullable<int> MarmaladeID4 { get; set; }
    
        public virtual Marmalade Marmalade { get; set; }
        public virtual Marmalade Marmalade1 { get; set; }
        public virtual Marmalade Marmalade2 { get; set; }
        public virtual Marmalade Marmalade3 { get; set; }
        public virtual ICollection<TBM> TBM { get; set; }
    }
}
