//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarmaladeApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gogolev_marmaladeEntities : DbContext
    {
        public Gogolev_marmaladeEntities()
            : base("name=Gogolev_marmaladeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BoxMarmalade> BoxMarmalade { get; set; }
        public DbSet<Marmalade> Marmalade { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<TBM> TBM { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<TM> TM { get; set; }
        public DbSet<User> User { get; set; }
    }
}
