//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarmaladeApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marmalade
    {
        public Marmalade()
        {
            this.BoxMarmalade = new HashSet<BoxMarmalade>();
            this.BoxMarmalade1 = new HashSet<BoxMarmalade>();
            this.BoxMarmalade2 = new HashSet<BoxMarmalade>();
            this.BoxMarmalade3 = new HashSet<BoxMarmalade>();
            this.TM = new HashSet<TM>();
        }
    
        public int id { get; set; }
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public bool Halal { get; set; }
        public string EnergyValue100gKilojoleOrCalories { get; set; }
        public decimal Gramm { get; set; }
        public string Compound { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<BoxMarmalade> BoxMarmalade { get; set; }
        public virtual ICollection<BoxMarmalade> BoxMarmalade1 { get; set; }
        public virtual ICollection<BoxMarmalade> BoxMarmalade2 { get; set; }
        public virtual ICollection<BoxMarmalade> BoxMarmalade3 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<TM> TM { get; set; }
    }
}
