//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarmaladeApp.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Supplier
    {
        public Supplier()
        {
            this.Marmalade = new HashSet<Marmalade>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Marmalade> Marmalade { get; set; }

        public string MarmaladesNames => string.Join(", ", Marmalade.Select(m => m.Name));
    }
}
