//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarmaladeApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TBM = new HashSet<TBM>();
            this.TM = new HashSet<TM>();
        }
    
        public int id { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public bool OrderCompleted { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
        public Nullable<bool> CanceledTicket { get; set; }
    
        public virtual ICollection<TBM> TBM { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TM> TM { get; set; }
    }
}
