//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarmaladeApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM
    {
        public int MarmaladeID { get; set; }
        public int Amount { get; set; }
        public int TIcketID { get; set; }
    
        public virtual Marmalade Marmalade { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
